### PR TITLE
karmada operator - inital-commit 

### PR DESCRIPTION
**Pull request by riverzhang**
Signed-off-by: RongZhang [zhangrong@vivo.com](mailto:zhangrong@vivo.com)
What type of PR is this?
karmada-operator - inital-commit
Part of https://github.com/karmada-io/karmada-operator/issues/2

### CODE REVIEW

**Comment by RainbowMango** [comment]
Hi @riverzhang Please sign your commits.

**Comment by RainbowMango** [comment]
Hi @riverzhang Does this ready for review or move forward?

**Comment by riverzhang** [comment]
> Hi @riverzhang Does this ready for review or move forward?
@RainbowMango  Now we're ready to review the code.

**Comment by riverzhang** [comment]
@RainbowMango Now we're ready to review the code.

**Pull request closed without merging**
